# Generated by Django 5.1.5 on 2025-01-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        help_text="Графический файл (фотография товара).", upload_to="images/", verbose_name="Image"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Объявление, связанное с этим изображением.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="board.advertisement",
                        verbose_name="Advertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
