# Generated by Django 5.1.5 on 2025-01-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Название товара или услуги.", max_length=150, verbose_name="Title"),
                ),
                ("description", models.TextField(help_text="Описание товара или услуги.", verbose_name="Description")),
                ("price", models.PositiveIntegerField(help_text="Цена товара или услуги.", verbose_name="Price")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания объявления.",
                        verbose_name="Date of creation",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Создатель объявления.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(help_text="Содержание отзыва.", verbose_name="Text")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата и время создания отзыва.", verbose_name="Date of creation"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Объявление, под которым оставлен отзыв.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_comments",
                        to="board.advertisement",
                        verbose_name="Advertisement",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Автор отзыва.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ("created_at",),
            },
        ),
    ]
